app = "video-captions"
primary_region = "ord"  # Chicago - change this to a region closer to you

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# Set OpenAI API key using:
# flyctl secrets set OPENAI_API_KEY=your_api_key_here

[mounts]
  source = "video_data"
  destination = "/app/uploads"

[mounts.paths]
  "/app/static/output" = "persistent"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024